<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.0.40</Version>
    <AssemblyVersion>1.0.40.0</AssemblyVersion>
    <FileVersion>1.0.40.0</FileVersion>
    <InformationalVersion>1.0.40</InformationalVersion>
    <Product>MDM Updater</Product>
    <AssemblyTitle>MDM.Updater</AssemblyTitle>
    <RootNamespace>MDM.Updater</RootNamespace>
    <AssemblyName>MDM.Updater</AssemblyName>
    <ApplicationIcon>Assets\mdm.ico</ApplicationIcon>
  </PropertyGroup>
</Project>